#!/bin/bash
# =============================================================================
# LiveKit Cluster Deployment Script
# https://github.com/livekit/livekit
# =============================================================================
# Run from deploy directory. Requires: PUBLIC_IP or LIVEKIT_PUBLIC_IP, TURN_DOMAIN
# Usage: ./deploy.sh [--skip-certs]
# =============================================================================

set -e

DEPLOY_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$DEPLOY_DIR"

# -----------------------------------------------------------------------------
# Configuration - override via environment
# -----------------------------------------------------------------------------
PUBLIC_IP="${LIVEKIT_PUBLIC_IP:-${PUBLIC_IP}}"
TURN_DOMAIN="${TURN_DOMAIN:-${PUBLIC_IP}}"
REGION="${LIVEKIT_REGION:-us-east-1}"

# Generate credentials if not set
REDIS_PASSWORD="${REDIS_PASSWORD:-$(openssl rand -base64 32)}"
TURN_CREDENTIAL="${TURN_CREDENTIAL:-$(openssl rand -base64 24)}"
API_KEY="${LIVEKIT_API_KEY:-livekit_$(openssl rand -hex 8)}"
API_SECRET="${LIVEKIT_API_SECRET:-$(openssl rand -base64 32)}"

# -----------------------------------------------------------------------------
# Validation
# -----------------------------------------------------------------------------
if [ -z "$PUBLIC_IP" ]; then
  echo "ERROR: Set LIVEKIT_PUBLIC_IP or PUBLIC_IP (your server's public IP)"
  echo "  export LIVEKIT_PUBLIC_IP=1.2.3.4"
  exit 1
fi

SKIP_COTURN=false
if [ "$1" = "--skip-certs" ]; then
  SKIP_COTURN=true
  echo "Deploying without coturn (--skip-certs)"
elif [ ! -f "certs/fullchain.pem" ] || [ ! -f "certs/privkey.pem" ]; then
  echo "ERROR: TLS certs not found. Place Let's Encrypt certs in certs/"
  echo "  See certs/README.md for instructions"
  echo "  Or run with --skip-certs to deploy without coturn"
  exit 1
fi

# -----------------------------------------------------------------------------
# Create /opt/livekit and copy files
# -----------------------------------------------------------------------------
echo "Creating /opt/livekit..."
sudo mkdir -p /opt/livekit
sudo cp -r "$DEPLOY_DIR"/* /opt/livekit/ 2>/dev/null || true
cd /opt/livekit

# -----------------------------------------------------------------------------
# Generate .env
# -----------------------------------------------------------------------------
echo "Generating .env..."
cat > .env << EOF
REDIS_PASSWORD=$REDIS_PASSWORD
LIVEKIT_PUBLIC_IP=$PUBLIC_IP
TURN_HOST=$TURN_DOMAIN
TURN_CREDENTIAL=$TURN_CREDENTIAL
LIVEKIT_API_KEY=$API_KEY
LIVEKIT_API_SECRET=$API_SECRET
LIVEKIT_REGION=$REGION
EOF

# -----------------------------------------------------------------------------
# Generate livekit.yaml from template
# -----------------------------------------------------------------------------
echo "Generating livekit.yaml..."
if [ "$SKIP_COTURN" = true ]; then
  cat > livekit.yaml << EOF
# LiveKit Server - generated by deploy.sh (no coturn)
port: 7880

redis:
  address: 127.0.0.1:6379
  password: $REDIS_PASSWORD
  db: 0

rtc:
  port_range_start: 50000
  port_range_end: 60000
  tcp_port: 7881
  use_external_ip: true

keys:
  $API_KEY: $API_SECRET

region: $REGION

logging:
  level: info
  pion_level: error
EOF
else
  cat > livekit.yaml << EOF
# LiveKit Server - generated by deploy.sh
port: 7880

redis:
  address: 127.0.0.1:6379
  password: $REDIS_PASSWORD
  db: 0

rtc:
  port_range_start: 50000
  port_range_end: 60000
  tcp_port: 7881
  use_external_ip: true
  turn_servers:
    - host: $TURN_DOMAIN
      port: 3478
      protocol: udp
      username: livekit
      credential: $TURN_CREDENTIAL
    - host: $TURN_DOMAIN
      port: 5349
      protocol: tls
      username: livekit
      credential: $TURN_CREDENTIAL

keys:
  $API_KEY: $API_SECRET

region: $REGION

logging:
  level: info
  pion_level: error
EOF
fi

# -----------------------------------------------------------------------------
# Generate coturn turnserver.conf (when coturn enabled)
# -----------------------------------------------------------------------------
if [ "$SKIP_COTURN" = false ]; then
  echo "Generating coturn config..."
  mkdir -p coturn
  sed -e "s|PLACEHOLDER_EXTERNAL_IP|$PUBLIC_IP|g" \
      -e "s|PLACEHOLDER_TURN_REALM|$TURN_DOMAIN|g" \
      -e "s|PLACEHOLDER_TURN_CREDENTIAL|$TURN_CREDENTIAL|g" \
      coturn/turnserver.conf > coturn/turnserver.conf.new
  mv coturn/turnserver.conf.new coturn/turnserver.conf
fi

# -----------------------------------------------------------------------------
# Export .env for docker-compose
# -----------------------------------------------------------------------------
set -a
source .env
set +a

# -----------------------------------------------------------------------------
# Start containers
# -----------------------------------------------------------------------------
echo "Starting containers..."
if [ "$SKIP_COTURN" = true ]; then
  docker compose up -d
else
  docker compose -f docker-compose.yml -f docker-compose.coturn.yml up -d
fi

# -----------------------------------------------------------------------------
# Wait and verify
# -----------------------------------------------------------------------------
echo "Waiting for LiveKit to start..."
sleep 5

for i in {1..12}; do
  if curl -s -o /dev/null -w "%{http_code}" "http://127.0.0.1:7880" 2>/dev/null | grep -q "200\|404\|405"; then
    echo "LiveKit is reachable on port 7880"
    break
  fi
  if [ $i -eq 12 ]; then
    echo "WARNING: LiveKit may not be ready. Check: docker compose logs livekit-server"
  fi
  sleep 2
done

# Health check - LiveKit responds on 7880 (WebSocket upgrade or HTTP)
HEALTH_URL="http://127.0.0.1:7880"
HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" "$HEALTH_URL" 2>/dev/null || echo "000")
if [ "$HTTP_CODE" != "000" ]; then
  echo "LiveKit reachable on port 7880 (HTTP $HTTP_CODE)"
else
  echo "Note: Verify manually: curl -s $HEALTH_URL"
fi

# -----------------------------------------------------------------------------
# Output credentials
# -----------------------------------------------------------------------------
SERVER_URL="ws://${PUBLIC_IP}:7880"
if [ -n "$LIVEKIT_DOMAIN" ]; then
  SERVER_URL="wss://${LIVEKIT_DOMAIN}"
fi

echo ""
echo "============================================================================="
echo "LiveKit Deployment Complete"
echo "============================================================================="
echo ""
echo "API Key:    $API_KEY"
echo "API Secret: $API_SECRET"
echo "Server URL: $SERVER_URL"
echo ""
echo "Save these credentials securely. They are also in /opt/livekit/.env"
echo ""
echo "Verify: curl -s http://127.0.0.1:7880"
echo "Logs:   docker compose -f /opt/livekit/docker-compose.yml logs -f"
echo "============================================================================="
